# Generated by Django 2.2.1 on 2021-02-17 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название опроса')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('end_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опросы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('type', models.CharField(choices=[('Ответ текстом', 'Ответ текстом'), ('Ответ с одним вариантом', 'Ответ с одним вариантом'), ('Ответ с несколькими вариантами', 'Ответ с несколькими вариантами')], max_length=64, verbose_name='Тип вопроса')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Interview')),
            ],
        ),
    ]
