# Generated by Django 2.2.1 on 2021-02-17 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.CreateModel(
            name='AnswerQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=256, verbose_name='Ответ для вопроса')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Question')),
            ],
            options={
                'verbose_name': 'Ответ на вопрос',
                'verbose_name_plural': 'Ответы на вопросы',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, verbose_name='Ответ')),
                ('answe_choice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest.AnswerQuestion')),
                ('interview_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Interview')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest.Question')),
            ],
        ),
    ]
