# Generated by Django 2.2.1 on 2021-02-17 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_auto_20210217_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
